name: Node Bug Report
description: Create a report to help us fix any problems for the npm package
assignees: systemsoftware
labels: [ "node", "bug" ]

body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: method
    attributes:
      label: Method
      description: Which API method threw the error.
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: Device info
      description: Node & package version, device model & os version.
    validations:
      required: false
